name: Blog
description: Michael Mao
meta_description: "Personal Blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://blog.michaelmao.ca'
permalink: '/:title'
google_analytics: 'UA-58311516-1'

# Details for the RSS feed generator
url:            'http://blog.michaelmao.ca'
author:         'Michael Mao'
