markdown: kramdown
highlighter: rouge

name: Blog
description: Michael Mao's Blog
author: Michael Mao

url: 'https://blog.michaelmao.ca'
baseurl: ''
permalink: '/:title'

# site options
logo: false
paginate: 10

google_analytics: 'UA-58311516-1'
disqus: 'michael340'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
